spring:
  application:
    name: yuzong-ai-code-mother
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuzong_ai_code_mother
    username: root
    password: 122333123
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      #有账号密码的要设置账号密码
      password:
      ttl: 3600  # 过期时间：1小时
      database: 0   # 配置的时候无法赋值database所以这里不要了
  # redis管理session 配置--session放在redis的时间
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期--- 在浏览器过期的时间
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yuzong.yuzongaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# mermaid文本生图MCP生成架构图绘制工具
# 备注：mac当中需要配置mmdc-path，否则idea获取不到
# 路径获取：在终端输入 which mmdc
# 去需要调用路径的位置调用mmdcPath：
#    @Value("${mermaid.mmdc-path:mmdc}")
#    private String mmdcPath;
mermaid:
  mmdc-path: /Users/yuzong/.nvm/versions/node/v20.20.2/bin/mmdc
